// Mocks generated by Mockito 5.4.6 from annotations
// in pipeline_calculation_app/test/services/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:convert' as _i4;
import 'dart:typed_data' as _i6;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:pipeline_calculation_app/models/calculation_record.dart' as _i8;
import 'package:pipeline_calculation_app/models/parameter_set.dart' as _i9;
import 'package:pipeline_calculation_app/services/local_data_service.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i3.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i3.Future<_i2.Response>);

  @override
  _i3.Future<_i2.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i3.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i3.Future<_i2.Response>);

  @override
  _i3.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i4.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i3.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i3.Future<_i2.Response>);

  @override
  _i3.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i4.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i3.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i3.Future<_i2.Response>);

  @override
  _i3.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i4.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i3.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i3.Future<_i2.Response>);

  @override
  _i3.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i4.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i3.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i3.Future<_i2.Response>);

  @override
  _i3.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<_i6.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i3.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i3.Future<_i6.Uint8List>);

  @override
  _i3.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i3.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_1(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocalDataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataService extends _i1.Mock implements _i7.LocalDataService {
  MockLocalDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> saveCalculationRecord(_i8.CalculationRecord? record) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCalculationRecord,
          [record],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<_i8.CalculationRecord?> getCalculationRecord(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalculationRecord,
          [id],
        ),
        returnValue: _i3.Future<_i8.CalculationRecord?>.value(),
      ) as _i3.Future<_i8.CalculationRecord?>);

  @override
  _i3.Future<List<_i8.CalculationRecord>> getAllCalculationRecords() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCalculationRecords,
          [],
        ),
        returnValue: _i3.Future<List<_i8.CalculationRecord>>.value(
            <_i8.CalculationRecord>[]),
      ) as _i3.Future<List<_i8.CalculationRecord>>);

  @override
  _i3.Future<List<_i8.CalculationRecord>> getPendingCalculationRecords() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingCalculationRecords,
          [],
        ),
        returnValue: _i3.Future<List<_i8.CalculationRecord>>.value(
            <_i8.CalculationRecord>[]),
      ) as _i3.Future<List<_i8.CalculationRecord>>);

  @override
  _i3.Future<List<_i8.CalculationRecord>> getPendingSyncRecords() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSyncRecords,
          [],
        ),
        returnValue: _i3.Future<List<_i8.CalculationRecord>>.value(
            <_i8.CalculationRecord>[]),
      ) as _i3.Future<List<_i8.CalculationRecord>>);

  @override
  _i3.Future<void> updateCalculationRecord(_i8.CalculationRecord? record) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCalculationRecord,
          [record],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCalculationRecord(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCalculationRecord,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveParameterSet(_i9.ParameterSet? parameterSet) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveParameterSet,
          [parameterSet],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i9.ParameterSet?> getParameterSet(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getParameterSet,
          [id],
        ),
        returnValue: _i3.Future<_i9.ParameterSet?>.value(),
      ) as _i3.Future<_i9.ParameterSet?>);

  @override
  _i3.Future<List<_i9.ParameterSet>> getAllParameterSets() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllParameterSets,
          [],
        ),
        returnValue:
            _i3.Future<List<_i9.ParameterSet>>.value(<_i9.ParameterSet>[]),
      ) as _i3.Future<List<_i9.ParameterSet>>);

  @override
  _i3.Future<List<_i9.ParameterSet>> getPendingParameterSets() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingParameterSets,
          [],
        ),
        returnValue:
            _i3.Future<List<_i9.ParameterSet>>.value(<_i9.ParameterSet>[]),
      ) as _i3.Future<List<_i9.ParameterSet>>);

  @override
  _i3.Future<void> updateParameterSet(_i9.ParameterSet? parameterSet) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateParameterSet,
          [parameterSet],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteParameterSet(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteParameterSet,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
